// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCJAScuPPVUyH2Uo82gOV5x9l5JdpZzY',
    appId: '1:113113919660:web:6b8e2d4bd3f30d980e6f09',
    messagingSenderId: '113113919660',
    projectId: 'grocery-list-0',
    authDomain: 'grocery-list-0.firebaseapp.com',
    databaseURL: 'https://grocery-list-0-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-list-0.appspot.com',
    measurementId: 'G-DEYJYZBTWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcEQPucr8Y5OUdEgpTsZcyL3yEE7-1fU',
    appId: '1:113113919660:android:f51ee49e74336c920e6f09',
    messagingSenderId: '113113919660',
    projectId: 'grocery-list-0',
    databaseURL: 'https://grocery-list-0-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-list-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ExKO6GBn7Qos9PEMQ-90fnFHwrYZquk',
    appId: '1:113113919660:ios:da1b1c530653b7f00e6f09',
    messagingSenderId: '113113919660',
    projectId: 'grocery-list-0',
    databaseURL: 'https://grocery-list-0-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-list-0.appspot.com',
    iosClientId: '113113919660-1mu35j6pndmm4avf2ivgp387kq25linr.apps.googleusercontent.com',
    iosBundleId: 'com.grocerylist.app',
  );
}
